# Generated by Django 3.2.7 on 2021-10-03 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_auto_20211002_1526'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='modul',
            new_name='module',
        ),
    ]
